const allData = [
    ['Top repositories', '主要存储库'],
    ['By default, the feed shows events from repositories you sponsor or watch, and people you follow.', '默认情况下，提要显示来自您赞助或观看的存储库的事件，以及您关注的人。'],
    ['Repositories and people you may like', '您可能喜欢的存储库和人员'],
    ['Who people are following', '人们在关注谁'],
    ['Issues and pull requests from repositories', '发布和从存储库中提取请求'],
    ['Repositories that are created or forked by people', '有人创建或分支的存储库'],
    ['Repositories being starred by people', '存储库被人标星'],
    ['Relevant projects or people that are being sponsored', '被赞助的相关项目或人员'],
    ['Update posts from repositories', '更新存储库中的帖子'],
    ['Special discussion posts from repositories', '来自存储库的特殊讨论帖子'],
    ['Include events from starred repositories', '包括标星存储库中的事件'],
    ['Recommendations', '推荐'],
    ['Follows', '遵循'],
    ['Repository activity', '存储库活动'],
    ['GitHub Website', 'GitHub 网站'],
    ['GitHub Docs', 'GitHub 文档'],
    ['GitHub Support', 'GitHub 支持'],
    ['GitHub Community', 'GitHub 社区'],
    ['Starred', '已标星'],
    ['Star', '标星'],
    ['Give feedback', '反馈'],
    ['Dashboard', '仪表盘'],
    ['Trending', '趋势'],
    ['Activity', '活动'],
    ['Community', '社区'],
    ['released', ' 已发布'],
    ['Jump to', '跳转'],
    [`You're seeing this because of your activity.`, '你看到这些是因为你的活动。'],
    ['Owners', '所有者'],
    ['Sponsor', '赞助'],
    ['Unstar this repository', '取消此存储库的标星'],
    ['Show less activity like this', '减少此类活动'],
    ['Feed item options', '活动选项'],
    ['Recommended for you', '为你推荐'],
    ['Trending repositories', '热门趋势项目'],
    ['Home', '主页'],
    ['Search syntax tips', '搜索语法提示'],
    ['Your Copilot', '你的 Copilot'],
    ['Your stars', '你的标星'],
    ['Your gists', '你的依据'],
    ['Your organizations', '你的组织'],
    ['Your enterprises', '你的企业'],
    ['Your sponsors', '你的赞助者'],
    ['Enter a valid URL', '输入有效的URL'],
    ['Setup notifications', '设置通知'],
    ['Sets the', '设置'],
    ['Approved header', '批准标头'],
    ['to automatically approve the message in a read-only or moderated mailing list.', '在只读或审核邮件列表中自动批准邮件。'],
    ['Whitespace separated email addresses (at most two).', '用空格分隔电子邮件地址（最多两个）。'],
    ['Asterisk (*) denotes a required field', '星号（*）表示必填字段'],
    ['Setup email addresses to receive notifications when push events are triggered.', '设置电子邮件地址，以便在触发推送事件时接收通知。'],
    [`There aren't any GitHub Apps installed on this repository.`, '此存储库上没有安装任何GitHub应用程序。'],
    ['GitHub Apps augment and extend your workflows on GitHub with commercial, open source, and homegrown tools.', 'GitHub应用程序通过商业，开源和本地工具增强和扩展GitHub上的工作流程。'],
    ['GitHub Apps', 'GitHub应用程序'],
    ['Installed GitHub Apps', '安装GitHub应用程序'],
    ['Secrets and variables', '秘密和变量'],
    ['Deploy keys', '部署密钥'],
    ['Code security', '代码安全'],
    ['GitHub Enterprise', 'GitHub 企业版'],
    ['There are no runners configured', '没有配置运行程序'],
    ['Learn more about using runners', '了解更多关于使用运行器的信息'],
    ['to run actions on your own servers.', '，在您自己的服务器上运行操作。'],
    ['Network', '网络'],
    ['Features', '特征'],
    ['Rename', '重命名'],
    ['Classic branch protections have not been configured', '未配置经典分支保护'],
    ['Private repository', '私有仓库'],
    ['private repository', '私有仓库'],
    ['Manage', '管理'],
    ['Manage access', '管理访问权限'],
    ['collaborators have access to this repository. Only you can contribute to this repository.', '协作者可以访问这个存储库。只有您可以对这个存储库做出贡献。'],
    ['Only those with access to this repository can view it', '只有有权访问此存储库的人才能查看它'],
    ['Rules', '规则'],
    ['Rulesets', '规则设置项'],
    ['Try GitHub Enterprise', '试用 GitHub Enterprise'],
    ['Learn more about the visibility of your GitHub Pages site.', '了解有关GitHub Pages网站可见性的更多信息。'],
    ['GitHub Pages is designed to host your personal, organization, or project pages from a GitHub repository.', 'GitHub Pages旨在从GitHub存储库中托管您的个人，组织或项目页面。'],
    ['With a GitHub Enterprise account, you can restrict access to your GitHub Pages site by publishing it privately. You can use privately published sites to share your internal documentation or knowledge base with members of your enterprise. You can try GitHub Enterprise risk-free for 30 days.', '使用GitHub Enterprise帐户，您可以通过私下发布来限制对GitHub Pages网站的访问。您可以使用私人发布的网站与企业成员共享您的内部文档或知识库。您可以免费试用GitHub Enterprise 30天。'],
    ['Learn more about GitHub Pages', '了解更多关于GitHub Pages的信息'],
    ['Upgrade or make this repository public to enable Pages', '升级或使此存储库公开以启用Pages'],
    ['is designed to host your personal, organization, or project pages from a GitHub repository.', '旨在从GitHub存储库中托管您的个人，组织或项目页面。'],
    ['Prebuild configuration', '预构建配置'],
    ['Set up prebuild', '设置预构建'],
    ['Learn more about setting up prebuilds', '了解有关设置预构建的更多信息'],
    ['Prebuild configurations speed up Codespace creations significantly by pre-executing all the tasks required to build your development environment.', '预构建配置通过预执行构建开发环境所需的所有任务，显著加快了代码空间的创建。'],
    ['There are no prebuilds configured for this repository', '没有为此存储库配置预构建'],
    ['Webhooks Guide', 'Webhooks指南'],
    ['Runners', '运行器'],
    ['Learn more about self-hosted runners', '了解更多关于自助运行器的信息'],
    ['Host your own runners and customize the environment used to run jobs in your GitHub Actions workflows.', '托管您自己的运行程序，并自定义用于在GitHub Actions工作流中运行作业的环境。'],
    ['Webhooks', '网络钩子'],
    ['Dependencies', '依赖关系'],
    ['The default branch is considered the “base” branch in your repository, against which all pull requests and code commits are automatically made, unless you specify a different branch.', '默认分支被认为是存储库中的基本分支，所有的拉取请求和代码提交都是根据它自动进行的，除非您指定了一个不同的分支。'],
    ['Learn more about signing off on commits', '了解有关签署提交的更多信息'],
    ['Developer Certificate of Origin (DCO)', '开发商产地来源证（DCO）'],
    [`Enabling this setting will require contributors to sign off on commits made through GitHub’s web interface. Signing off is a way for contributors to affirm that their commit complies with the repository's terms, commonly the`, '启用此设置需要贡献者在通过GitHub的web界面提交时签名。签名是贡献者确认他们的提交符合存储库条款的一种方式，通常是'],
    ['Require contributors to sign off on web-based commits', '要求贡献者在基于网络的提交上签字'],
    ['Template repositories let users generate new repositories with the same directory structure and files.', '模板存储库允许用户生成具有相同目录结构和文件的新存储库。'],
    ['Learn more about template repositories', '了解更多关于模板存储库的信息'],
    ['Template repository', '模板存储库'],
    ['Enable the dependency graph', '启用依赖关系图'],
    ['Learn more about how we use your data', '了解更多关于我们如何使用您的数据'],
    ['The dependency graph is not enabled for this repository. Click on "Enable the dependency graph" below to enable it.', '此存储库未启用依赖关系图。点击下面的“启用依赖关系图”来启用它。'],
    ['Track this repository’s dependencies and sub-dependencies', '跟踪此存储库的依赖项和子依赖项'],
    ['Policy', '政策'],
    ['Help your community understand how to securely report security vulnerabilities for your project.', '帮助您的社区了解如何安全地报告项目的安全漏洞。'],
    ['Enable the dependency graph', '启用依赖关系图'],
    ['Vulnerability alerts', '漏洞警报'],
    ['Code scanning alerts •', '扫码警报 •'],
    ['Advanced Security is only available for Organizations', '高级安全仅适用于组织'],
    ['Find out more', '了解更多'],
    ['Dependabot alerts •', 'Dependabot 警报 •'],
    ['Get notified when one of your dependencies has a vulnerability', '当您的某个依赖项存在漏洞时获得通知'],
    ['Enable Dependabot alerts', '启用Dependabot警报'],
    ['Security policy •', '安全策略 •'],
    ['Disabled', '禁用'],
    ['Enable', '启用'],
    ['Suggested for this repository', '建议用于此存储库'],
    ['Actions Performance Metrics', '操作性能指标'],
    ['Actions Usage Metrics', '操作使用指标'],
    ['Define how users should report security vulnerabilities for this repository', '定义用户应该如何报告此存储库的安全漏洞'],
    ['Set up a security policy', '设置安全策略'],
    ['Security overview', '安全概述'],
    ['Link a project', '链接项目'],
    ['Your workspaces in the cloud', '你的云的工作区'],
    ['More workflows', '更多工作流'],
    ['Deployments', '部署'],
    ['No codespaces', '没有代码空间'],
    ['(separate with spaces)', '（用空格隔开）'],
    ['Branch', '分支'],
    ['Find or create a branch...', '查找或创建分支...'],
    ['Learn more about codespaces...', '了解更多关于代码空间的信息…'],
    ['Create codespace on main', '在main上创建代码空间'],
    [`You don't have any codespaces with this repository checked out`, '您没有签出此存储库的任何代码空间'],
    ['Dismiss suggestions', '驳回建议'],
    ['Add projects to view them here.', '添加项目并在此处查看它们。'],
    ['Provide quick access to relevant projects.', '提供对相关项目的快速访问。'],
    ['Skip this and set up a workflow yourself', '跳过此步骤，自己建立一个工作流'],
    ['forks', ' 分支'],
    ['Forks', ' 分支'],
    ['Welcome to projects', '欢迎参与项目'],
    ['Built like a spreadsheet, project tables give you a live canvas to filter, sort, and group issues and pull requests. Tailor them to your needs with custom fields and saved views.', '项目表就像电子表格一样构建，为您提供了一个实时画布，用于过滤、排序和分组问题以及拉取请求。使用自定义字段和保存的视图根据您的需求进行定制。'],
    ['Welcome to pull requests!', '欢迎拉取请求！'],
    ['Welcome to issues!', '欢迎提问！'],
    ['Readme', ' 自述'],
    ['Contact', '联系'],
    ['Security alerts', '安全警报'],
    ['Manage cookies', '管理 Cookie'],
    ['watching', ' 查看'],
    ['Do not share my personal information', '不要分享我的个人信息'],
    ['Announcements', '公告'],
    ['Suggested workflows', '建议工作流'],
    ['Based on your tech stack', '基于你的技术栈'],
    ['Actions', '动作'],
    ['Codespaces', '代码空间'],
    ['Participating and @mentions', '参与和@提及'],
    ['Only receive notifications from this repository when participating or @mentioned.', '仅在参与或@提及时接收来自此存储库的通知。'],
    ['Custom', '自定义'],
    ['Select events you want to be notified of in addition to participating and @mentions.', '除了参与和@提及之外，选择您希望收到通知的事件。'],
    ['Ignore', '忽略'],
    ['Never be notified.', '永远不要收到通知。'],
    ['All Activity', '所有活动'],
    ['Notified of all notifications on this repository.', '通知此存储库上的所有通知。'],
    ['No releases published', '未发布任何版本'],
    ['Reset to default', '重置为默认'],
    ['See what the GitHub community is most excited about today.', '看看今天GitHub社区最活跃的是什么。'],
    ['Spoken Language', '口语'],
    ['Language', '语言'],
    ['Date range', '日期范围'],
    ['Developers', '开发者'],
    ['Topics', '专题'],
    ['Browse popular topics on GitHub.', '在GitHub上浏览热门专题。'],
    ['All featured topics', '所有专题'],
    ['Collections', '收藏'],
    ['Curated lists and insight into burgeoning industries, topics, and communities.', '策划列表和洞察新兴行业，主题和社区。'],
    ['Create a collection', '创建收藏'],
    // 新增加
    [`Recent Repositories`, `最近仓库`],
    [`Search or jump to…`, `搜索并跳转至...`],
    [`Issues`, `问题`],
    [`Pull`, `合并`],
    [`request`, `请求`],
    [`s`, ``],
    [`Marketplace`, `市场`],
    [`Explore`, `探索`],
    [`Following`, `关注者`],
    [`Find a repository…`, `查找仓库`],
    [`Latest changes`, `最新变化`],
    [`hours ago`, `小时前`],
    [`days ago`, `天前`],
    [`New`, `新建`],
    [`Explore repositories`, `探索存储库`],
    [`Explore more →`, `探索更多 →`],
    [`Set status`, `设置状态`],
    [`Your profile`, `个人信息`],
    [`Your repositories`, `个人仓库`],
    [`Your codespaces`, `你的 codespaces`],
    [`Your projects`, `你的项目`],
    [`Signed in as`, `登陆账户为`],
    [`Feature preview`, `功能预览`],
    [`Upgrade`, `升级`],
    [`Try Enterprise`, `尝试企业版`],
    [`Help`, `帮助`],
    [`Settings`, `设置`],
    [`Sign out`, `退出`],
    [`Overview`, `概述`],
    [`Repositories`, `仓库`],
    [`Projects`, `项目`],
    [`Packages`, `包`],
    [`Popular repositories`, `流行的仓库`],
    [`Edit profile`, `编辑个人信息`],
    [`followers`, ` 被关注`],
    [`following`, ` 关注`],
    [`Public`, `公开`],
    [`Customize your pins`, `定义你的置顶项目`],
    [`Contribution settings`, `贡献设置`],
    [`Pinned`, `置顶`],
    [`Learn how we count contributions`, `了解我们如何计算贡献`],
    [`Code review`, `代码评审`],
    [`Pull requests`, `合并请求`],
    [`Commits`, `提交`],
    [`Contribution activity`, `贡献活动`],
    [`Show more activity`, `显示更多活动`],
    [`Code`, `代码`],
    [`Go to file`, `转至文件`],
    [`Add file`, `添加文件`],
    [`About`, `关于`],
    [`Pin`, `置顶`],
    [`Pin this repository to your profile`, `置顶这个项目到你的个人信息`],
    [`New repository`, `新建仓库`],
    [`Import repository`, `导入仓库`],
    [`New organization`, `新建组织`],
    [`Create a new release`, `创建一个新的版本`],
    [`Publish your first package`, `发布你的第一个包`],
    [`Releases`, `发布`],
    [`Packages `, `包`],
    [`No packages published`, `没有发布任何软件包`],
    [`Languages`, `语言`],
    [`Show more`, `显示更多`],
    [`Recent activity`, `最新动态`],
    [
        `When you take actions across GitHub, we’ll provide links to that activity here.`,
        `当你在 GitHub 上采取行动时，我们会在这里提供该活动的链接。`,
    ],
    [`More`, `更多`],
    [`Subscribe to your news feed`, `订阅你的 feed`],
    [`Blog`, `博客`],
    [`Shop`, `商店`],
    [`Contact GitHub`, `联系 Github`],
    [`Pricing`, `定价`],
    [`Training`, `培训`],
    [`Status`, `状态`],
    [`Security`, `安全`],
    [`Terms`, `团队`],
    [`Privacy`, `隐私`],
    [`Docs`, `文档`],
    [`New project`, `新建项目`],
    [`Activity  overview`, `活动概览`],
    [`Projects`, `项目`],
    [`Security`, `安全`],
    [`Insights`, `统计`],
    [`Create new file`, `创建新的文件`],
    [`Upload files`, `上传文件`],
    [`Code`, `代码`],
    [`Local`, `本地`],
    [`Clone`, `克隆`],
    [`Open with GitHub Desktop`, `在 Github 桌面程序中打开`],
    [`Download ZIP`, `下载压缩包`],
    [`New codespace`, `新建 codespace`],
    [`Less`, `更少`],
    [`Select type`, `选择类型`],
    [`Type`, `类型`],
    [`Language`, `语言`],
    [`Sort`, `排序`],
    [`Private`, `私有`],
    [`Select language`, `选择语言`],
    [`Select order`, `选择顺序`],
    [`Last updated`, `最近更新`],
    [`Create a new repository`, `创建一个新的仓库`],
    [`Owner`, `拥有者`],
    [`Repository name`, `仓库名字`],
    [`Description`, `描述`],
    [`(optional)`, `(可选)`],
    [
        `Anyone on the internet can see this repository. You choose who can commit.`,
        `互联网上的任何人都可以看到这个存储库。你选择谁能够提交。`,
    ],
    [
        `You choose who can see and commit to this repository.`,
        `你可以选择谁可以看到和提交这个版本库。`,
    ],
    [
        `A repository contains all project files, including the revision history. Already have a project repository elsewhere?`,
        `一个仓库包含所有项目文件，包括修订历史。在其他地方已经有一个项目库了？`,
    ],
    [`Import a repository.`, `导入仓库`],
    [
        `Skip this step if you’re importing an existing repository.`,
        `如果你要导入一个已有的版本库，请跳过这一步。`,
    ],
    [
        `Choose which files not to track from a list of templates.`,
        `从一个模板列表中选择哪些文件不需要跟踪。`,
    ],
    [
        `This is where you can write a long description for your project.`,
        `在这里，你可以为你的项目写一个长的描述。`,
    ],
    [
        `A license tells others what they can and can't do with your code.`,
        `许可证告诉别人他们可以和不可以用你的代码做什么。`,
    ],
    [
        `You are creating a public repository in your personal account.`,
        `你正在你的个人账户中创建一个公共库。`,
    ],
    [`Initialize this repository with:`, `用以下方式初始化这个存储库：`],
    [`Create repository`, `创建仓库`],
    [
        `Great repository names are short and memorable. Need inspiration? How about`,
        `伟大的仓库名称是简短而令人难忘的。需要灵感吗？比如 `,
    ],
    [`Your personal account`, `你的个人账户`],
    [`Public profile`, `公开资料`],
    [`Name`, `名字`],
    [`Change username`, `修改用户名`],
    [`Account`, `账户`],
    [`Export account data`, `导出账户数据`],
    [`Appearance`, `外观`],
    [`Accessibility`, `无障碍设施`],
    [`Notifications`, `通知`],
    [`Access`, `访问`],
    [`Personal billing`, `个人帐单`],
    [`Emails`, `邮件`],
    [`Billing and plans`, `账单和计划`],
    [
        `This is a list of SSH keys associated with your account. Remove any keys that you do not recognize.`,
        `这是与你的账户相关的 SSH 密钥的列表，删除任何你不认识的密钥`,
    ],
    [`Organizations`, `组织`],
    [`You are not a member of any organizations.`, `你不是任何组织的成员  `],
    [`Archives`, `归档`],
    [`Security log`, `安全日志`],
    [`Sponsorship log`, `赞助日志`],
    [`No sponsorship activity in this time period`, `这段时间内没有赞助活动`],
    [`Sign in to GitHub`, `登录到 Github`],
    [`Username or email address`, `用户名或邮箱`],
    [`Password`, `密码`],
    [`Sign in`, `登录`],
    [`New to GitHub?`, `刚来 Github？`],
    [`Create an account`, `创建一个账户`],
    [`Forgot password?`, `忘记密码？`],
    [`Create an account`, ``],
    [
        `Label issues and pull requests for new contributors`,
        `为新的贡献者标记问题和合并请求`,
    ],
    [`Filters`, `过滤`],
    [`New Issue`, `新问题`],
    [`There aren’t any open issues.`, `没有任何公开的问题。`],
    [`Signing in…`, `登录中...`],
    [`Edit repository details`, `编辑仓库详情信息`],
    [`Website`, `网站`],
    [`Cancer`, `取消`],
    [`Save changes`, `保存修改`],
    [`Protect this branch`, `保护这个分支`],
    [`Get started with GitHub Actions`, `开始使用 Github Actions`],
    [
        `Build, test, and deploy your code. Make code reviews, branch management, and issue triaging work the way you want. Select a workflow to get started.`,
        `构建、测试和部署你的代码。使代码审查、分支管理和问题分流以你想要的方式进行。选择一个工作流程来开始。`,
    ],
    [`Browse all categories`, `浏览所有类型`],
    [`Automation`, `自动化`],
    [`Deployment`, `部署`],
    [`Continuous integration`, `持续集成`],
    [`Reporting`, `报告`],
    [`General`, `常规`],
    [`Public email`, `公开的邮箱`],
    [`Bio`, `个人简历`],
    [`URL`, `网站`],
    [`Twitter username`, `Twitter 用户名`],
    [`Company`, `公司`],
    [`Location`, `地址`],
    [`Contributions & Activity`, `贡献和活动`],
    [`Successor settings`, `继承人设置`],
    [`You have not designated a successor.`, `你还没有指定继承人`],
    [`Delete account`, `删除账户`],
    [
        `Once you delete your account, there is no going back. Please be certain.`,
        `一旦你删除了你的账户，就不能够找回了，请慎重`,
    ],
    [`Display current local time`, `显示当前的本地时间`],
    [`Keyboard shortcuts`, `快捷键`],
    [`Subscriptions`, `订阅`],
    [`Verified domains`, `验证的域名`],
    [`There are no verified domains.`, `没有经过验证的域名`],
    [`Password and authentication`, `密码和身份验证`],
    [`Change password`, `修改密码`],
    [`Old password`, `旧密码`],
    [`New password`, `新密码`],
    [`Confirm new password`, `确认新的密码`],
    [`Two-factor authentication`, `两步验证`],
    [`Confirm new password`, `确认新的密码`],
    [`Confirm access`, `确认访问`],
    [`Confirm`, `确认`],
    [`Who has access`, `谁有权限`],
    [`Code and automation`, `代码和自动化`],
    [`Default branch`, `默认分支`],
    [`Branch protection rules`, `分支保护规则`],
    [`Protected tags`, `保护标签`],
    [`Environments`, `环境变量`],
    [`Code security and analysis`, `代码安全性和分析`],
    [`Integrations`, `集成`],
    [`Email notifications`, `邮件通知`],
    [`Collaborators`, `合作者`],
    [`Contributors`, `贡献者`],
    [`Community Standards`, `社区标准`],
    [`Traffic`, `流量`],
    [`Code frequency`, `代码频率`],
    [`Dependency graph`, `依赖图`],
    [`Contributors`, `贡献者`],
    [`You can`, `你可以`],
    [`@mention`, `@`],
    [
        `other users and organizations to link to them.`,
        `其他用户和组织来链接它们`,
    ],
    [`Save`, `保存`],
    [`Cancel`, `取消`],
    [`Welcome to the all-new projects`, `欢迎来到全新的项目`],
    [`No open projects`, `没有开放的项目`],
    [`Add a bio`, `添加个人简介`],
    [`Loading more...`, `正在加载中`],
    [
        `Your popular repositories will now be shown instead of your pins.`,
        `你的热门仓库现在将显示，而不是你的置顶`,
    ],
    [`Unpin`, `不置顶`],
    [`Your pins have been updated.`, `你的置顶已经更新了`],
    [`Advanced search`, `高级搜索`],
    [`Branches`, `分支`],
    [`Social Preview`, `社交预览`],
    [
        `Upload an image to customize your repository’s social media preview.`,
        `上传图片来定制你仓库的社交媒体预览`,
    ],
    [`Pull Requests`, `合并请求`],
    [`Danger Zone`, `危险区`],
    [`Change repository visibility`, `修改仓库的可见性`],
    [`Transfer ownership`, `转让所有权`],
    [`This repository is currently public.`, `这个仓库当前是公开的`],
    [`Archive this repository`, `归档这个仓库`],
    [
        `Mark this repository as archived and read-only.`,
        `将此版本库标记为归档和只读`,
    ],
    [`Delete this repository`, `删除这个仓库`],
    [
        `Once you delete a repository, there is no going back. Please be certain.`,
        `一旦你删除了这个仓库，就不能够撤回了，请确认`,
    ],
    [`Are you absolutely sure?`, `你真的确定吗？`],
    [`Change visibility`, `修改可见性`],
    [`Change to private`, `修改为私有`],
    [`Transfer`, `转移`],
    [`Edit status`, `编辑状态`],
    [`Busy`, `忙`],
    [`Clear status`, `清除状态`],
    [`Never`, `从不`],
    [`Your main branch isn't protected`, `你的 main 分支不是受保护的`],
    [
        `Protect this branch from force pushing or deletion, or require status checks before merging.`,
        `保护这个分支不被强行推送或删减，或要求在合并前进行状态检查 `,
    ],
    [`Learn more`, `学习更多`],
    [`Branch protection rule`, `分支保护规则`],
    [`Protect your most important branches`, `保护你最重要的分支`],
    [`Achievements`, `成就`],
    [`Send feedback`, `发送反馈`],
    [`Choose a license`, `选择许可证`],
    [`Learn more.`, `学习更多`],
    [`Import your project to GitHub`, `导入你得项目到 Github`],
    [`Inbox`, `收件箱`],
    [`Prev`, `上页`],
    [`Next`, `下页`],
    [`Saved`, `保存`],
    [`Done`, `完成`],
    [`Manage notifications`, `管理通知`],
    [`See more`, `查看更多`],
    [`Include in the home page`, `显示在页面上`],
    [`Discussions`, `讨论`],
    [`Users`, `用户`],
    [`This repository is currently private.`, `这个仓库当前是私有的`],
    [`Lists`, `列表`],
    [`Create list`, `创建列表`],
    [`Pushes`, `推送`],
    [
        `Limit how many branches and tags can be updated in a single push`,
        `限制一次推送中可以更新多少个分支和标签`,
    ],
    [`I want to make this repository private`, `我想要让这个仓库变为私有`],
    [`I have read and understand these effects`, `我已经阅读并理解了这些影响`],
    [`New issue`, `新建问题`],
    [`Labels`, `标签`],
    [`New milestone`, `新建里程碑`],
    [`Milestones`, `里程碑`],
    [`You haven’t created any Milestones.`, `你还没有创建任何里程碑。`],
    [`Edit`, `编辑`],
    [`Delete`, `删除`],
    [`Close`, `关闭`],
    [`Success`, `完成`],
    [`to search`, `搜索`],
    [`Search`, `搜索`],
    [`Create your first project`, `创建您的第一个项目`],
    [
        `Ready to start building? Create a repository for a new idea or bring over an existing repository to keep contributing to it.`,
        `准备好开始构建了吗？为新的想法创建一个存储库，或导入一个存储库以继续为它做出贡献。`,
    ],
    [`Filter`, `筛选`],
    [`Events`, `活动`],
    [`Activity you want to see on your feed`, `您希望在推送中看到的活动`],
    [`Stars`, ` 星`],
    [`stars`, ` 星`],
    [`Default`, `默认值`],
    [`Tags`, `标签`],
    [`Watch`, `查看`],
    [`Fork`, `复刻`],
    [`Starred`, `标星`],
    [`Switch branches/tags`, `查看所有分支/标签`],
    [`Profile picture`, `简介图片`],
    [`SSH and GPG keys`, `SSH和GPG密钥`],
    [`Cancel changes`, `取消更改`],
    [`Commit changes...`, `提交更改...`],
    [``, ``],
    [``, ``],
    [``, ``],
    [``, ``],
    [``, ``],
    [``, ``],
    [``, ``],
    [``, ``],
];

const MutationObserverConfig = {
    childList: true,
    subtree: true,
    attributeFilter: ["data-label"],
    characterData: true,
};

const observer = new MutationObserver(function (mutations) {
    const treeWalker = document.createTreeWalker(
        document.body,
        NodeFilter.SHOW_ALL,
        {
            acceptNode: function (node) {
                if (
                    node.nodeType === 3 ||
                    (node.hasAttribute &&
                        (node.hasAttribute("data-label") ||
                            node.hasAttribute("placeholder") ||
                            node.hasAttribute("value")))
                ) {
                    return NodeFilter.FILTER_ACCEPT;
                } else {
                    return NodeFilter.FILTER_SKIP;
                }
            },
        },
        false
    );
    let dataMap = new Map();
    allData.forEach(([key, val]) => {
        if (key && !dataMap.has(key)) {
            dataMap.set(key, val);
        }
    });
    let currentNode = treeWalker.currentNode;
    while (currentNode) {
        if (currentNode.nodeType === 3) {
            let key1 = currentNode.textContent
                .replace(/^\s*|\s*$/g, "")
                .replace(/\s+/g, " ");
            if (dataMap.has(key1)) currentNode.textContent = dataMap.get(key1);
        } else {
            let key2 = currentNode.getAttribute("data-label");
            if (key2 && dataMap.has(key2))
                currentNode.setAttribute("data-label", dataMap.get(key2));
            let key3 = currentNode.getAttribute("placeholder") || "";
            if ((key3 = key3.trim())) {
                if (dataMap.has(key3))
                    currentNode.setAttribute("placeholder", dataMap.get(key3));
            }
            let key4 = currentNode.getAttribute("value");
            if (currentNode.tagName == "INPUT" && dataMap.has(key4)) {
                currentNode.setAttribute("value", dataMap.get(key4));
                let key5 = currentNode.getAttribute("data-signin-label");
                let key6 = currentNode.getAttribute("data-disable-with");
                currentNode.setAttribute("data-signin-label", dataMap.get(key5));
                currentNode.setAttribute("data-disable-with", dataMap.get(key6));
            }
        }
        currentNode = treeWalker.nextNode();
    }
});

observer.observe(document.body, MutationObserverConfig);
